site_name: Compensation Knowledge Graph
site_description: Obsidian Vault → 자동 크롤링/규칙 학습/5WHY/크로스체크
site_url: https://foxli250917.github.io/compensation-research

docs_dir: ObsidianVault/Compensation   # Vault를 웹 문서로 사용
site_dir: site

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - 홈: 보상작용.md
  - 규칙(자동): 보상작용-규칙(자동).md
  - 템플릿: 5WHY-보상작용-템플릿.md
  - 논문들:
      - papers/:
          - index: index