name: Compensation Crawler Bot

on:
  schedule:
    - cron: "*/10 * * * *"   # 10분마다 실행
  workflow_dispatch:         # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests unidecode

      - name: Run crawler
        run: |
          python compensation_crawler_bot.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update: compensation rules and notes [skip ci]" || echo "No changes"
          git push
